import streamlit as st
import random

st.title("hola amorsi c:")
st.write("te amo mucho y queria hacerte algo para demostrarte lo mucho que te amo")
st.write("este es un 100 reasons de porque te amo amorsi, te amo mushio, presiona el boton para ver las razones")

clicked = st.button("presiona aca")

def razonAleatoria():
    razones = [ "por tu carita HERMOSAAAA, me encanta tu sonrisita bella",
                "por tenerme tanta paciencia en mis cagadas",
                "porque siempre escuchas musica conmigo y me enseñas musica demasiado buena y eres la mejor en la musica",
                "me encanta como cantas y porque a veces me cantas para dormir",
                "porque siempre me reclamas cuando me quiero ir al baño o me voy a dormir antes que tu y quieres hacer todo juntos",
                "porque eres la MEJOOOOOR cocinando, morsi eres una michelin shef enserio",
                "porque eres una engreida preciosa hermosa bella tiernaaaa, me fasina ienarte de amor",
                "por la carita que haces cuando pruebas algo rico y cierras los ojitos y disfrutas el bocado",
                "porque eres la mas risueña y me encanta ver tu sonrisita y escuchar tu risa siempre",
                "por tu carita de enojada cuando estas concentrada que parece que odias a todo el mundo",
                "porque me fascina escushar como pides algo de delivery ndqwodnoqidnoqoidqmwidqwd",
                "por la carita que haces cuando te ries y como se achinan tus ojitos hermosos cafes 'super oscuros'",
                "porque eres una dormilona y siempre quieres 5 minutitos mas y me encanta darterlos",
                "porque cuando estas acurrucadita en tu camita estas como una bolita y me dan ganas de acostarme contigo",
                "por lo aventurera que eres y porque caminas muchisimo y me encantaria ser mas como tu y me encanta que me ieves contigo aunque a beses odie que me duelan los piesitos",
                "por lo TIERNA que eres cunado me pides algo y me dices amosiiii pofis",
                "morsi porque eres la mas shambeadora y me consientes siempre",
                "porque siempre me motivas a seguir adelante y you hold me accountable siempre, siento que siempre podria contar contigo",
                "porque eres mi mejor amiga y te puedo contar lo que sea que me pase sin tener miedo que me vayas a juzgar",
                "porque eres SUPER INTELIGENTE MORSI y en mushios sentidos y me encanta conversar y tener debates contigo de las cosas y aprender de como piensas",
                "porque eres demasiado passionate por las cosas y me contagias tu pasion, ES QUE TE AMO MUCHO",
                "porque eres super artsy morsi y alternativa y cool e interesante y increible y hermosa y me encanta lo artistica que eres sipsisp",
                "proque eres demasiado genial con manualidades tipo WTF AMORSI como que hicisite un planetario para marce y a mi me hicist flores y una radio eres como art attack pero mas talented y bella y hermosa",
                "porque eres demasiado cool y me encanta estar contigo e interactuar como couple porque eres demasiado cool, no se como explicalro pero como que tienes un aura demasiado cool morsi",
                "porque tienes unos people skills INCREIBLES y siento que puedes hacerte amiga de cualquiera",
                "porque te encantan los juegos de mesa y eres super competitiva y eres demasiado buena amorsi te amo por eso porque me da ganas de deicr ala mi amorsi es demasiado inteligente y cool",
                "porque eres una iorona amorsi y eres super sensible e in touch with your emotions mushias veces y me dan ganas de darte un abracito enorme y decirt eque todo estara bien pero solo me sale intentar hacerte reir :c"
                "porque eres una geek del rock argentino y lo considero demasiado cool que conozcas tanto de la historia de carly garcia o spinetta",
                "porque eres una disney kid y porque tienes una TARJETA DE DISNEY",
                "porque eres una starbucks/matcha girlie que CONSIDERO MUY COOL, creo que te considero una persona super cool en general morsi sispsisips",
                "porque cantamos juntos duetoooos, como cuando cantamos las canciones de rapunzel LO QUE ME FASCINOOOO",
                "porque me llenas de amor todos los dias, siento que tu presencia es un sol enorme que ilumina mi vida y me mantiene calientito",
                "porque luchas mucho por tus sueños, estas en nueva york ahorita y yo a veces me pongo a pensar y tipo no puedo comprender lo lejos que estas pero me llenas de orgullo mucho y se que lograras tus metas amorsi",
                "porque resuelves siempre morsi, me acuerdo cuando me ayudaste a decorar mi cuarto con posters",
                "porque te tiras shanshos y me dices escuse moi amorsi despues y cuando io lo hago me obligas a decirte",
                "porque a ir a orinar le dices ir a hacer pipi, me da MUCHO CUTEEE MORSI",
                "porque me encanta darte besos, es el mejor taste y la mejor sensacion en el mundo entero",
                "porque cuando nos abrazamos i feel whle and complete and i feel like que crearon nuestroa brasos y pechos para abrazarse el uno al otro",
                "porque when we are together its never enough physical touch e incluso cuando estamos naked cuddling no es suficiente y quisiera meterme dentro de tu piel morsi",
                "porque despues de mushio ahora nos decimos bebe y es lo mejor del mundo y del uniberso",
                "morsi porque te encanta el shisme y siempre me cuentas el shisme a mi porque a mi tambien me encanta el shisme",
                "porque eres igualita a los emojis parados, EN ESPECIAL AL EMOJI PARADO DEL EMOJI PARADO CON LO SLENTESITOS esa eres tu morsi spsispsispisp",
                "porque eres super espiritual morsi y le sabes mushio y tienes tu tarotista y todo y ala eres la mejol",
                "porque tu voz es super preciosa y creo que es mi definision de belleza sipspsip, en especial cinado me dices AMORSIIII",
                "porque siempre tienes tus spots favoritas y me los presentas siempre",
                "porque tienes infinitas layers y siento que siempre i can peel more off y conocerte masymasymas aunque ya hayan pasado 5 añios desde que nos conocimos",
                "porque you are my first everything y mi last everything",
                "porque eres una posesiva y un pokito loca morsi",
                "porque eres una fashion girlie y me encanta que lo seas y que te vistas tan genial y me encantaria comprarte toda al ropa del mundo",
                "porque te encanta apple y ves los specs de los productos y sabes mas que yo sobre como utilizarlo y eres perfeta",
                "porque eres buenisima tomando fotos y me encanta que me enseñes a tomar fotos y me encanta las fotos que tomas",
                "porque no me puedo imaginar un mundo sin ti miamor",
                "porque eres super funny morsi, siempre me sacas una sonrisa y me elevas mi estado de animo",
                "porque lite eres mi shot of espresso de todos los dias y me aumentas mi energia pero al mismo tiempo podria quedarme durmiendo contigo un dia entero",
                "porque le sabes mushio a la medicina y podria confiarte mi salud cuando estoy con tos o gripe y me podrias nurse back to life y eres genial e incrieble",
                "porque eres super directa y outspoken con las cosas y a veces cuando me involucra o cosas asi me incomoda un poko pero al mismo tiempo me encanta porque siento que es super admirable de tu parte morsi",
                "porque te encantan encantan encantan las flores y me encantó dartelas y te seguire dando porque te las mereces y porque escogias las flores para tu casa de shiquita y ere la mejor",
                "porque minigiu is full of stories and problems and joy y me encanta when she comes out y me encanta escusharla, sus historias y me encantaria volver en el tiempo y conocerla como miniafo",
                "porque eres una ex theater kid y me hiciste ver hamilton y me obsesione y hacias covers de canciones y las escuchaba y decia wow esta shica es increible",
                "porque me hiciste ver glee y veiamos en tu sala y teniamos momentos super intimos juntos viendo y ahora siempre que veo me acuerdo de ti y de tu compañia",
                "porque eres la mejor cooking partner que podria pedir y me enseñas a hacer cosas super riquisimas y las compares con mi familia y nunca jamas de podria dejar porque cocinas riquisisisisimo segun el taxita sispisps",
                "porque fuiste mi primera partner en mi primer concierto en el hola fest y vimos a lala y canto caramelo y yo creo que fue para nosotros sisispps",
                "porque eres una teachers pet y tienes una relacion de putamadre con tus profesores y te quierne muchisimo porque eres la MEJOOOR",
                "porque das siempre los mejores consejos morsi y das siempre el mejor comfort y tu hombro y tu regazo y tu presencia siempre son el mejor lugar para llorar",
                "i feel like u light up the room anywhere, anytime you go somewhere y todos lo notamos morsi",
                "porque eres una flojisima y siempre te tengo que decir que hagas las cosas y me dices morsi nopii y yo te digo morsi enserioo y me haces caso y me quedo acompañandote",
                "porque me parece super gracioso que puedes dormir en cualquier lado e incluso PARADA en el frio",
                "porque eres una friolenta y io siempre toi calentito y te puedo calentar siempre isisisp",
                "porque me parece super admirable que estas en TRES shambas y estudiando y es como que wow mi amorsi es demasiado increible",
                "porque mi familia te ama mushiomushiomushio y ellos tambien piensan que eres un solsito y que te encanta cocinar y que eres muy cool y fashionista como mi mami",
                "porque me encantan tus rulos y me pareces una diosa griega literalmente t eocmo ENTERA amor",
                "porque cuando dormimos juntos te duermes acostada en mi pecho y sin importar cuanto calor haga no te mueves de ahi",
                "porque siempre estas dispuesta a escuchar las cosas que se me ocurren, que me gustan y que me obsesionan y lo haces con una sonrisa gigante y me hace sentir super especial. ahora te agradezco por leer lo obesionado que estoy contigo bebe",
                "porque me haces la persona mas feliz del universo",
                "porque eres pocket sized morsi y te puedo ievar a donde sea en mi bolsillo y porque soy 4 cm mas alto que tupi y siento que somos el uno para el otro",
                "porque tienes las cejas mas bonitas hermosas preciosas del planeta entero morsi",
                "porque siempre me haces mis cejas y me haces skincare y me pones musho aloe vera y cremitas y porque pronto nos haremos el skincare todos los dias",
                "porque nuestra cancion es y por siempre sera me rehuso y porque para nosotros hay infinitos atardeceres para seguirnos conociendos amorsi",
                "porque siempre me ayudas a mi y a tus amigos y a todas las personas que te importan de las maneras que puedes y siempre das todo de ti haciendolo, no te merecemos amorsi",
                "porque eres la mejor del mundo entero dando regalos, enserio amorsi eres super detallista y siempre pones atencion y te acuerdas de las cosas que importan y das detalles preiosossosisisismos",
                "porque los tragos que haces son super riquisimos y me emborrashan un poco pero me encanta estarlo junto ati",
                "porque siempre hagas lo que hagas you stand out ALWAYYYSSSSSS AMOR, you are so so so sos sosososos SOOOO special",
                "porque tu juego favorito era pvz y el mio tambien y creoq eu deberiamos jugar juntitos",
                "porque eres la morra con la camara analoga que siempre guarda los momentos que pasan y you treasure them osea LITE TIENES un baul de los RECUERDOS OSEA TE AMO",
                "porque tu cosa favorita en el mundo entero es ver el sunset en una playita escushando al mar y teniendo paz y me gustaria estar ahi contigo",
                "porque creo sinceramente que eres la representacion de la luna encarnada porque eres un poco misteriosa y me das las mismas vibes pero al mismo tiempo eres un sol enorme y calentito",
                "porque mushias veces te vistes como la profesora de arte del colegio y me fascina mushisisisimo como no tienes idea amorsi, tambien porque te encantan las faldas y las faldas con POLKA DOTS osea watefok",
                "porque subes toda tu vida en tus reposts de tiktok, aunqeu a beses me juega una mala pasada",
                "porque sueñop en vivir un año entero contigo en la playa y amanecer todos los dias y tirarnos a la arena, nadar en el mar y volver a la casa que tengamos, prepararnos algo que comer y lounge todo el dia juntos y luego salir juntos todos de blanco tu con un summer dress y yo con una camisa blanca y short blanco y estar todos los dias asi",
                "porque cuando no hablamos siento que te veo en todos lados morsi, las caras de las personas se warpean a tu car ay todo me recuerda a ti y se que para ti e igual",
                "porque siempre que salimos terminamos besandonos mushisiisisissimo y ablnado de la bida y no puedo tener enough de ti cuando te veo",
                "porque eres la mas nostalgica y siempre te gusta look back on simpler times y me hace sentir tambien apreciar todos los momentos que tuvimos juntos",
                "porque hacer alfajores contigo es lo mejor y hacer mousse juntos tambien, me encanta ir al mercado contigo a conseguir los ingredientes tambien",
                "porque creaste una BANDA y sacaste un EP a spotify dedicado a mi (allegedly), y yo ocmo que WOW OSEA WOW AMORSI QUE COOLQ UE ERES DIOS",
                "porque tienes un paladar super exigente y puedes decirme que especia tiene cada cosa y hasta en que año mataron a la carne y todote y es como que ala amorsi te amo como sabes tanto eres una genia",
                "porque no se si lo dije antes pero eres la mujer mas preciosa del planeta entero, nadie se compara a tu nivel de belleza y hermosura y perfeccion amor enserio te digo",
                "porque tu juego favorito para jugar cartas es POTO SUCIO KJASKJAKJSAJKJ amorsi watefok",
                "porque eres brasileña y me encanta cuando hablas portugues y que seas color uebo en serio morsi me encantas",
                "porque tu pelo es castaño aunque era negro porque le pusiste mil colorantes y en un momento fuiste pelirroja morsi buelbe a tu pelirrojes que te qeudaba super bonito y increible pero tambien quedate con pelo negro porque te ves hermosa asi tambien pero tambien quedate castaña porque te ves bellisima asi tambien",
                "porque tienes los mejores disfraces para halloween y porque siempre que te alistas te grabas un tiktok presumiendo tu maquillaje y tengo que deicr que me encanta tu forma de maquillarte demasiado demasiado demasiado me fascina y tengo que controlar que tanto te beso cuando te haces tus labios porque se te va el labial pero sipi y lo unico malo es que no me pasas los tik toks cuando temrinas." ]
    index = random.randint(0,len(razones))
    return razones[index]

if (clicked):
    st.write(razonAleatoria())
